-- Esquema para Supabase (pegar en el SQL Editor de Supabase)

-- 1. Crear tabla de cálculos
create table if not exists public.calculations (
  id bigint generated by default as identity primary key,
  expression text not null,
  result text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad a nivel de fila (RLS)
alter table public.calculations enable row level security;

-- 3. Políticas de acceso (lectura, inserción y borrado para anon y authenticated)
drop policy if exists "Permitir lectura publica" on public.calculations;
create policy "Permitir lectura publica"
  on public.calculations for select
  to anon, authenticated
  using (true);

drop policy if exists "Permitir insercion publica" on public.calculations;
create policy "Permitir insercion publica"
  on public.calculations for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Permitir borrado publico" on public.calculations;
create policy "Permitir borrado publico"
  on public.calculations for delete
  to anon, authenticated
  using (true);
